[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python main.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[build.nixpacksPlan]
providers = ["python"]

[build.nixpacksPlan.phases.setup]
nixPkgs = ["python311", "ffmpeg", "libsndfile", "alsa-lib", "pulseaudio"]

[build.nixpacksPlan.phases.install]
cmds = [
    "python -m pip install --upgrade pip",
    "pip install -r requirements.txt"
]

[build.nixpacksPlan.phases.build]
cmds = [
    "python -c \"import nltk; nltk.download('punkt')\"",
    "playwright install chromium"
]

[build.nixpacksPlan.start]
cmd = "python main.py"
